### ISSUE TITLE
Fixing(?) the last version Tag or moving directly to semantic versioning.

### ISSUE THREAD

**Issue by Happy86** [Selfnet/selfnet-wificonfig#5]
Moving the last Tag as proposed in #4 could break things. :D 

In the [F-Droid issue 951#note_184469267 (Izzy)](https://gitlab.com/fdroid/rfp/issues/951#note_184469267) we got the hint to [Semantic Versioning](https://semver.org/).

Either way I propose: 
* to either wait for the next functional change and then bump 
  * the version tag to v1.2 (git commit)
  * the android:versionCode to 4 (app/src/main/AndroidManifest.xml)
  * the android:versionName to 1.2 (app/src/main/AndroidManifest.xml)
* or to bump the version now without any functional changes
  * the android:versionCode to 4 (app/src/main/AndroidManifest.xml)
  * the android:versionName to 1.1.2 (app/src/main/AndroidManifest.xml)
  * the version tag v1.1.2 (git commit)

"Moving" a tag might breakt "things" as far as I understood.

@guserav What do you think about that? 

Will create a new pull request after we came to a conclusion here. :-)

**Comment by guserav** [comment]
As I don't see any functional changes ahead for this App I believe bumping the version is the best option.
